# Generated by Django 3.0.6 on 2020-08-08 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('aq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nickname', models.CharField(max_length=50)),
                ('startDate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('repeatable', models.BooleanField()),
                ('repeat_time', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('notify', models.BooleanField()),
                ('notification_time', models.DateTimeField()),
                ('aquariums', models.ManyToManyField(to='core.Aquarium')),
            ],
        ),
        migrations.CreateModel(
            name='PHMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(decimal_places=2, max_digits=3)),
                ('measure_time', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aquarium')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('param_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_order', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=50)),
                ('aq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aquarium')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measure_id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('time', models.BigIntegerField()),
                ('param_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aquarium')),
            ],
        ),
        migrations.CreateModel(
            name='AquariumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aquarium_images')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aquarium')),
            ],
        ),
    ]
