# Generated by Django 3.0.6 on 2020-06-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tank',
            new_name='Aquarium',
        ),
    ]
